In [1]:
import pickle
import glob
import random

import cv2
import numpy as np

from sklearn.linear_model import SGDClassifier, RidgeClassifier
from sklearn import svm, metrics

from matplotlib import pyplot as plt

In [2]:
path = './digits2/train/'

le = 0
for i in range(10):
    paths = glob.glob(path + str(i) + '/*.png')
    le += len(paths)

x_train = np.zeros((le, 120), dtype=np.float32)
y_train = np.zeros((le))

idx = 0
for i in range(10):
    paths = glob.glob(path + str(i) + '/*.png')
    for p in paths:
        img = cv2.imread(p, 0)
        img = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 5, 1)
        
        img = np.true_divide(img, 255.0)
        img = img.flatten()
                
        x_train[idx] = img
        y_train[idx] = i
        idx += 1

In [3]:
path = './digits2/test/'

le = 0
for i in range(10):
    paths = glob.glob(path + str(i) + '/*.png')
    le += len(paths)

x_test = np.zeros((le, 120), dtype=np.float32)
y_test = np.zeros((le))

idx = 0
for i in range(10):
    paths = glob.glob(path + str(i) + '/*.png')
    for p in paths:
        img = cv2.imread(p, 0)
        img = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 5, 1)
        
        img = np.true_divide(img, 255.0)
        img = img.flatten()
                
        x_test[idx] = img
        y_test[idx] = i
        idx += 1 

In [4]:
print(x_train.shape) 
print(x_test.shape) 
print(y_train.shape) 
print(y_test.shape) 

(47, 120)
(33, 120)
(47,)
(33,)


In [5]:
# clf = SGDClassifier(loss="hinge", penalty="l2")
# clf = RidgeClassifier(normalize=True)
clf = svm.SVC()

clf.fit(x_train, y_train)

pickle.dump(clf, open('SVC.ski', 'wb'))

In [6]:
tidx = 7
r = clf.predict(x_test[tidx].reshape(1, -1))
print(r, y_test[tidx])

[2.] 2.0


In [7]:
y_test_pred = clf.predict(x_test)

metrics.accuracy_score(y_test, y_test_pred)

0.9696969696969697

In [8]:
print(metrics.classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.67      0.80         3
         1.0       0.80      1.00      0.89         4
         2.0       1.00      1.00      1.00         3
         3.0       1.00      1.00      1.00         4
         4.0       1.00      1.00      1.00         3
         5.0       1.00      1.00      1.00         3
         6.0       1.00      1.00      1.00         4
         7.0       1.00      1.00      1.00         3
         8.0       1.00      1.00      1.00         2
         9.0       1.00      1.00      1.00         4

    accuracy                           0.97        33
   macro avg       0.98      0.97      0.97        33
weighted avg       0.98      0.97      0.97        33



In [9]:
print(metrics.confusion_matrix(y_test, y_test_pred))

[[2 1 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 4]]
